In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("C:\\Users\\91779\\Downloads\\tested.csv")
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [3]:
input = df.drop(['PassengerId', 'Name','SibSp', 'Cabin', 'Embarked','Parch','Ticket','Survived'], axis=1)
input.head()

Pclass     Sex   Age     Fare
0       3    male  34.5   7.8292
1       3  female  47.0   7.0000
2       2    male  62.0   9.6875
3       3    male  27.0   8.6625
4       3  female  22.0  12.2875

In [4]:
target=df.Survived
target.head()
#type (target)

0    0
1    1
2    0
3    0
4    1
Name: Survived, dtype: int64

In [5]:
input.columns[input.isna().any()]

Index(['Age', 'Fare'], dtype='object')

In [6]:
input.Age=input.Age.fillna(input.Age.mean())
input.Fare=input.Fare.fillna(input.Fare.mean())

In [7]:
input.columns[input.isna().any()]

Index([], dtype='object')

In [8]:
from sklearn.preprocessing import LabelEncoder
x=LabelEncoder()
input['Sex_n']=x.fit_transform(input.Sex)
input=input.drop('Sex',axis=1)
input.head()


Pclass   Age     Fare  Sex_n
0       3  34.5   7.8292      1
1       3  47.0   7.0000      0
2       2  62.0   9.6875      1
3       3  27.0   8.6625      1
4       3  22.0  12.2875      0

In [9]:
from sklearn.model_selection import train_test_split
input_train,input_test,target_train,target_test=train_test_split(input,target,test_size=0.2)

In [10]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier()
clf.fit(input_train,target_train)
clf.score(input_test,target_test)

1.0

In [11]:
clf.predict([[1,6,70,0]])

c:\Program Files\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [12]:
clf.predict_proba([[1,6,70,0]])

c:\Program Files\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [13]:
clf.predict([[1,35,50,1]])

c:\Program Files\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [14]:
clf.predict_proba([[1,35,50,1]])

c:\Program Files\Python311\Lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([[1., 0.]])

In [15]:
input_importances_

NameError: name 'input_train_importances_' is not defined