features as text

In [144]:
import numpy as np
import pandas as pd

In [145]:
df=pd.read_csv(r"C:\Users\91779\Downloads\archive (1).zip",encoding='ANSI')
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [146]:
df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1,inplace=True)
df.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [147]:
df.columns = ['label','input']
df.head()

label                                              input
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [148]:
df.groupby('label').describe()

input                                                               
      count unique                                                top freq
label                                                                     
ham    4825   4516                             Sorry, I'll call later   30
spam    747    653  Please call our customer service representativ...    4

In [149]:
df.shape

(5572, 2)

In [150]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()
input_vect=vectorizer.fit_transform(df.input)
input_vect,vectorizer.vocabulary_.get('my')

(<5572x8673 sparse matrix of type '<class 'numpy.int64'>'
 	with 73917 stored elements in Compressed Sparse Row format>,
 5223)

In [151]:
print(input_vect.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [152]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.input,df.label,test_size=0.25)
x_train.shape

(4179,)

In [153]:
x_train_vect=vectorizer.transform(x_train)
x_train_vect.shape

(4179, 8673)

In [154]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_vect,y_train)

MultinomialNB()

In [155]:
x_test_vect=vectorizer.transform(x_test)
model.score(x_test_vect,y_test)

0.9856424982053122

In [156]:
from sklearn.pipeline import Pipeline
clf=Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())])

In [157]:
clf.fit(x_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [158]:
clf.score(x_test,y_test)

0.9885139985642498

In [159]:
emails=['you got flat 100% discount','you should come tomorrow']
clf.predict(emails)

array(['spam', 'ham'], dtype='<U4')

In [160]:
clf.predict_proba(emails)

array([[3.17936861e-01, 6.82063139e-01],
       [9.99728988e-01, 2.71012363e-04]])

In [161]:
from nltk.stem.snowball import SnowballStemmer
stemmer=SnowballStemmer("english")

In [162]:
stemmer.stem('responsiveness')

'respons'

In [163]:
stemmer.stem('unresponsiveness')

'unrespons'

In [164]:
stemmer.stem('responsibility')

'respons'

In [167]:
stemmer.stem('uncertainity')

'uncertain'

Tffidf-Vectorizer

In [178]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer2 = TfidfVectorizer()
x = vectorizer2.fit_transform(corpus)
vectorizer2.get_feature_names_out()


print(x.shape)

(4, 9)


In [170]:
x.toarray()

array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])

In [180]:
vectorizer2.get_feature_names_out(),vectorizer2.vocabulary_.get('first')

(array(['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third',
        'this'], dtype=object),
 2)